let arr = [ 10, 8, 5, 4, 3, 2, 1]

let reduceRes = arr.reduce((acc, curr) => acc * curr, 1)
 

Array.prototype.myMap = function (cb){
    let temp =[]
    for(let i =0; i < this.length; i++){
        let newValue = cb(this[i], i, this)
        temp.push(newValue)
    }
    return temp
}

let res = arr.myMap(i => i + i)

const wordCount = (str) => str.trim().split(/\s+/).length;

const removeDuplicates = arr => arr.filter((item, index) => arr.indexOf(item) === index);

let newArr = [
    "Composed",
    "Conceived",
    "Created",
    "Designed",
    "Developed",
    "Devised",
    "Established",
    "Founded",
    "Generated",
    "Implemented",
    "Initiated",
    "Instituted",
    "Introduced",
    "Launched",
    "Led",
    "Opened",
    "Originated",
    "Pioneered",
    "Planned",
    "Prepared",
    "Produced",
    "Promoted",
    "Started",
    "Released",
    "Advised",
    "Coached",
    "Conducted",
    "Directed",
    "Guided",
    "Demonstrated",
    "Illustrated",
    "Led",
    "Managed",
    "Organized",
    "Performed",
    "Presented",
    "Taught",
    "Trained",
    "Mentored",
    "Spearheaded",
    "Authored",
    "Accelerated",
    "Achieved",
    "Allocated",
    "Completed",
    "Awarded",
    "Persuaded",
    "Revamped",
    "Influenced",
    "Assessed",
    "Clarified",
    "Counseled",
    "Diagnosed",
    "Educated",
    "Facilitated",
    "Familiarized",
    "Motivated",
    "Referred",
    "Rehabilitated",
    "Reinforced",
    "Represented",
    "Moderated",
    "Verified",
    "Adapted",
    "Coordinated",
    "Developed",
    "Enabled",
    "Encouraged",
    "Evaluated",
    "Explained",
    "Informed",
    "Instructed",
    "Lectured",
    "Stimulated",
    "Teamed",
    "Collaborated",
    "Influenced",
    "Volunteered",
    "Partnered",
    "Motivated",
    "Coached",
    "United",
    "Analyzed",
    "Assessed",
    "Classified",
    "Collated",
    "Defined",
    "Devised",
    "Established",
    "Evaluated",
    "Forecasted",
    "Identified",
    "Interviewed",
    "Investigated",
    "Researched",
    "Tested",
    "Traced",
    "Designed",
    "Interpreted",
    "Verified",
    "Uncovered",
    "Clarified",
    "Collected",
    "Critiqued",
    "Diagnosed",
    "Examined",
    "Extracted",
    "Inspected",
    "Inspired",
    "Organized",
    "Reviewed",
    "Summarized",
    "Surveyed",
    "Systemized",
    "Arranged",
    "Budgeted",
    "Composed",
    "Conceived",
    "Conducted",
    "Controlled",
    "Co-ordinated",
    "Eliminated",
    "Improved",
    "Itemised",
    "Modernised",
    "Operated",
    "Organised",
    "Planned",
    "Prepared",
    "Processed",
    "Produced",
    "Redesigned",
    "Reduced",
    "Refined",
    "Resolved",
    "Revised",
    "Scheduled",
    "Simplified",
    "Solved",
    "Streamlined",
    "Transformed",
    "Revamped",
    "Addressed",
    "Advised",
    "Arranged",
    "Authored",
    "Co-authored",
    "Co-ordinated",
    "Communicated",
    "Corresponded",
    "Counselled",
    "Developed",
    "Demonstrated",
    "Directed",
    "Drafted",
    "Enlisted",
    "Facilitated",
    "Formulated",
    "Guided",
    "Influenced",
    "Interpreted",
    "Interviewed",
    "Instructed",
    "Lectured",
    "Led",
    "Liaised",
    "Mediated",
    "Moderated",
    "Motivated",
    "Negotiated",
    "Persuaded",
    "Presented",
    "Promoted",
    "Proposed",
    "Publicized",
    "Recommended",
    "Reconciled",
    "Recruited",
    "Resolved",
    "Taught",
    "Trained",
    "Translated"]

   console.log(removeDuplicates(newArr))

   